Add springboot docker
AntonZhdanov/Book-Store pull request #11
Opened 2023-09-25 17:40 UTC by AntonZhdanov

2023-09-25 20:22 UTC, IvanFadieiev approved these changes
LGTM!)

2023-09-26 08:14 UTC, nacenik requested changes
GJ, let's improve it :)

2023-09-26 08:14 UTC, nacenik commented on docker-compose.yml
> +  book-store:
I'd recommend you change the order. Better to start services and then service that depends on others.

2023-09-26 08:14 UTC, nacenik commented on Dockerfile
> +ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
I'd also recommend you move this to the docker-compose instead of dockerfile

2023-09-27 06:55 UTC, boroda4436 approved these changes
Good job!

2023-10-23 18:48 UTC, merged