Add springboot test-for-book functionality
AntonZhdanov/Book-Store pull request #12
Opened 2023-09-28 00:50 UTC by AntonZhdanov

2023-09-28 11:38 UTC, keda-vlad approved these changes
Approved, but check my comments, it's optional maybe, but maybe will improve yore code)

2023-09-28 11:38 UTC, keda-vlad commented on src/main/java/com/example/bookstore/model/Book.java
> +@Setter
@Data contains @Getter and @Setter

2023-09-28 11:38 UTC, keda-vlad commented on src/test/java/com/example/bookstore/repository/BookRepositoryTest.java
> +    }
I'm not sure that u need this test, especially in repository test

2023-09-28 11:38 UTC, keda-vlad commented on src/test/java/com/example/bookstore/service/CategoryServiceImplTest.java
> +        fantasyCategoryDto.setDescription(fantasyCategory.getDescription());
A lot of repeats, maybe better to make constants or methods

2023-09-28 11:38 UTC, keda-vlad commented on src/test/resources/database/books/add-books.sql
> +insert into books (id, title, author, isbn, price, description, cover_image, is_deleted) values (4, 'A Game of Thrones', ' George RR Martin', 'some isbn4', 34, 'Description', 'Cover image', false);
U can make it by one insert
`insert into books (id, title, author, isbn, price, description, cover_image, is_deleted) values 
(1, '1984', 'George Orwell', '978-5-699-12014-7', 19, 'Description', 'Cover image', false), 
(2, 'The Lord of The Rings', 'J. R. R. Tolkien', 'some isbn2', 29, 'Description', 'Cover image', false),
(3, 'The Adventures of Sherlock Holmes', 'Sir Arthur Conan Doyle', 'some isbn3', 24, 'Description', 'Cover image', false),
(4, 'A Game of Thrones', ' George RR Martin', 'some isbn4', 34, 'Description', 'Cover image', false);
`

2023-10-03 14:07 UTC, andrii-hoienko requested changes
Gj! But still some improvements required

2023-10-03 14:07 UTC, andrii-hoienko commented on src/test/java/com/example/bookstore/controller/BookControllerTest.java
> +        // When
Please remove comments

2023-10-03 14:07 UTC, andrii-hoienko commented on src/test/java/com/example/bookstore/controller/BookControllerTest.java
> +        CreateBookRequestDto requestDto = new CreateBookRequestDto(
Please create contents for books and other objects and reuse them

2023-10-03 14:07 UTC, andrii-hoienko commented on src/test/java/com/example/bookstore/controller/BookControllerTest.java
> +        assertThat(response).hasSize(4);
Please make sure that not only size is expected but values as well

2023-10-03 14:07 UTC, andrii-hoienko commented on src/test/java/com/example/bookstore/service/CategoryServiceImplTest.java
> +        verify(categoryRepository, times(1)).findById(anyLong());
times(1) is set by default as far as I remember (check all tests)

2023-10-03 14:07 UTC, andrii-hoienko commented on src/test/java/com/example/bookstore/service/CategoryServiceImplTest.java
> +        verify(categoryRepository, times(1)).findById(anyLong());
Not necessary to verify that mocks are called (check all tests)

2023-10-16 15:17 UTC, vovasalyha approved these changes
Approving, but please check my comment

2023-10-16 15:17 UTC, vovasalyha commented on src/test/java/com/example/bookstore/service/CategoryServiceImplTest.java
> +        verify(categoryRepository).findById(anyLong());
you did not resolved Andrii's comment about redundant `verify` method calls, please check the documentation of `verify` method to better understand in which cases it is redundant.
<img width="653" alt="image" src="https://github.com/AntonZhdanov/Book-Store/assets/82539553/9b2c5e7b-a684-454a-a36b-c021e4f019e5">

2023-10-24 19:19 UTC, merged