Add tests for a shopping cart functionality
AntonZhdanov/Book-Store pull request #14
Opened 2023-10-20 14:15 UTC by AntonZhdanov

2023-10-20 14:22 UTC, AntonZhdanov commented
![TestWithCoverage](https://github.com/AntonZhdanov/Book-Store/assets/133981383/010e6faf-fe1b-4a87-8331-c76df3a63b45)

2023-10-23 16:04 UTC, vovasalyha requested changes
GJ, but see a couple of comments

2023-10-23 16:04 UTC, vovasalyha commented on src/test/java/com/example/bookstore/controller/CategoryControllerTest.java
> +                    new ClassPathResource("database/categories/add-categories.sql"));
you can use annotation based approach too

2023-10-23 16:04 UTC, vovasalyha commented on src/test/java/com/example/bookstore/controller/CategoryControllerTest.java
> +            ScriptUtils.executeSqlScript(connection,
you can use annotation based approach too

2023-10-23 16:04 UTC, vovasalyha commented on src/test/java/com/example/bookstore/service/CartItemServiceImplTest.java
> +        verify(cartItemRepository, times(1)).save(any(CartItem.class));
times(1) is by default, you don't need to specify it.

2023-10-23 16:04 UTC, vovasalyha commented on src/test/resources/database/cartitems/add-1984-to-cartitems.sql
> +insert into cart_items(id, shopping_cart_id, book_id, quantity, is_deleted) values (1, 1, 1, 2, false);
add empty lines where needed

2023-10-25 15:02 UTC, vovasalyha approved these changes

2023-10-26 14:16 UTC, merged