spring-web
AntonZhdanov/Book-Store pull request #2
Opened 2023-09-05 12:47 UTC by AntonZhdanov

2023-09-05 16:03 UTC, OlegStashkiv approved these changes

2023-09-06 14:09 UTC, vovasalyha requested changes
GJ. Let's improve it a bit.

2023-09-06 14:09 UTC, vovasalyha commented on pom.xml
> +			<artifactId>spring-boot-starter</artifactId>
Is this dependency required?

2023-09-06 14:09 UTC, vovasalyha commented on src/main/java/com/example/bookstore/BookStoreApplication.java
> +    private final BookService bookService;
Do you use BookService here?

2023-09-06 14:09 UTC, vovasalyha commented on src/main/java/com/example/bookstore/model/Book.java
> +    @Column(unique = true)
Specify `nullable` parameter too (and in all other not null fields, so hibernate can correctly validate you schema)

2023-09-06 14:09 UTC, vovasalyha commented on src/main/java/com/example/bookstore/repository/BookRepository.java
> +    Optional<Book> findBookById(Long id);
```suggestion
    Optional<Book> findById(Long id);
```

2023-09-06 14:09 UTC, vovasalyha commented on src/main/java/com/example/bookstore/repository/BookRepositoryImp.java
> +public class BookRepositoryImp implements BookRepository {
```suggestion
public class BookRepositoryImpl implements BookRepository {
```

2023-09-06 14:09 UTC, vovasalyha commented on src/main/java/com/example/bookstore/repository/BookRepositoryImp.java
> +                    "SELECT b FROM Book b", Book.class).getResultList();
```suggestion
                    "FROM Book", Book.class).getResultList();
```

2023-09-06 15:02 UTC, vovasalyha approved these changes

2023-09-08 11:50 UTC, merged