Add springboot-security
AntonZhdanov/Book-Store pull request #7
Opened 2023-09-12 21:43 UTC by AntonZhdanov

2023-09-13 12:44 UTC, IvanFadieiev requested changes
Look's good to me, some small change required:)

2023-09-13 12:44 UTC, IvanFadieiev commented on src/main/java/com/example/bookstore/exception/RegistrationException.java
> +}
According to task requirements we need to handle this exception in GlobalExceptionHandler

2023-09-13 12:44 UTC, IvanFadieiev commented on src/main/resources/db/changelog/changes/05-insert-roles-for-users.yaml
> +                  value: ROLE_ADMIN
add new line

2023-09-13 18:32 UTC, IvanFadieiev approved these changes
GJ! :)

2023-09-14 07:29 UTC, nacenik requested changes
Good solution, let's improve it :)

2023-09-14 07:29 UTC, nacenik commented on src/main/java/com/example/bookstore/dto/user/UserResponseDto.java
> +public class UserResponseDto {
if you start using features from Java 17+ like record, use them everywhere you can

2023-09-14 07:29 UTC, nacenik commented on src/main/java/com/example/bookstore/service/role/RoleServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Can't find role: " + roleName));
throw or custom exception or NoSuchElementException

2023-09-14 07:29 UTC, nacenik commented on src/main/java/com/example/bookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
Create constant for `"Bearer "` and instead of using regular int, use method `length()` to get a substring of bearer

2023-09-14 07:29 UTC, nacenik commented on src/main/java/com/example/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
Create constant for this value

2023-09-18 12:19 UTC, andrii-hoienko requested changes
Nice, I left minor comments

2023-09-18 12:19 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/service/user/UserServiceImpl.java
> +            throw new RegistrationException("this email is already in use");
please add details to error message

2023-09-18 12:19 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/JwtAuthenticationFilter.java
> +    private static final int BEARER_OFFSET = BEARER_PREFIX.length();
It is not necessary to create constants for thing that can be calculated

2023-09-18 12:19 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/JwtUtil.java
> +
```suggestion
```

2023-09-18 12:19 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new RegistrationException("Can't find user by email"));
add details to error message

2023-09-18 12:19 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/04-create-role-user-table.yaml
> +      author: anton
what if there are 2 antons in team?

2023-09-19 11:46 UTC, andrii-hoienko approved these changes
GJ

2023-09-29 12:40 UTC, merged