Add springboot-category-model
AntonZhdanov/Book-Store pull request #8
Opened 2023-09-13 22:25 UTC by AntonZhdanov

2023-09-14 07:56 UTC, Someboty requested changes
Great work! But did you check for lazy exception?

2023-09-14 07:56 UTC, Someboty commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    @Operation(summary = "Get a book by ID")
Copy+paste – evil)

2023-09-14 07:56 UTC, Someboty commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +        return categoryMapper.toDto(category);
Move it to service

2023-09-14 07:56 UTC, Someboty commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    public List<BookDtoWithoutCategoryIds> getBooksByCategoryId(@PathVariable Long id) {
You need pageable here too

2023-09-14 07:56 UTC, Someboty commented on src/main/java/com/example/bookstore/dto/book/BookDtoWithoutCategoryIds.java
> +    @Positive
Isn't it do same thing?

2023-09-14 07:56 UTC, Someboty commented on src/main/java/com/example/bookstore/model/Category.java
> +    private Set<Book> bookSet = new HashSet<>();
Why do you need it here?

2023-09-14 07:56 UTC, Someboty commented on src/main/java/com/example/bookstore/model/Category.java
> +}
Where it used?

2023-09-14 07:56 UTC, Someboty commented on src/main/java/com/example/bookstore/service/category/CategoryServiceImpl.java
> +        List<BookDtoWithoutCategoryIds> bookDtoWithoutCategoryIdsList = books
Maybe add method to repository?

2023-09-14 07:56 UTC, Someboty commented on src/main/resources/db/changelog/changes/06-create-category-table.yaml
> +      author: root
You have a pretty name)

2023-09-14 07:56 UTC, Someboty commented on src/main/resources/db/changelog/changes/07-create-books-categories-table.yaml
> +            constraintName: fk_book_category_book
```suggestion
                    foreignKeyName: categories.id
```

2023-09-18 14:59 UTC, vovasalyha requested changes
GJ. Let's improve it a bit

2023-09-18 14:59 UTC, vovasalyha commented on src/main/java/com/example/bookstore/dto/book/BookDtoWithoutCategoryIds.java
> +    @Min(0)
```suggestion
```

2023-09-18 14:59 UTC, vovasalyha commented on src/main/java/com/example/bookstore/dto/book/CreateBookRequestDto.java
> +        @NotNull @Min(0) @Positive BigDecimal price,
```suggestion
        @NotNull @Positive BigDecimal price,
```

2023-09-18 14:59 UTC, vovasalyha commented on src/main/java/com/example/bookstore/model/Category.java
> +    private Set<Book> bookSet = new HashSet<>();
I agree that it is redundant complexity and you can remove it, but it is for you to decide
```suggestion
    private Set<Book> books = new HashSet<>();
```

2023-09-18 14:59 UTC, vovasalyha commented on src/main/java/com/example/bookstore/service/category/CategoryServiceImpl.java
> +        Category category = categoryMapper.toModel(categoryDto);
You don't need this and next line

2023-09-18 14:59 UTC, vovasalyha commented on src/main/java/com/example/bookstore/service/category/CategoryServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2023-09-18 14:59 UTC, vovasalyha commented on src/main/java/com/example/bookstore/service/category/CategoryServiceImpl.java
> +        Category category = categoryRepository.findCategoryWithBooks(id);
Everything can be fetched in one query. Additionally, this method more suits to the services related to the book, not to the category

2023-09-18 14:59 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/07-create-books-categories-table.yaml
> +            columns:
add also constraint primary key (book_id, category_id)

2023-09-19 15:17 UTC, vovasalyha approved these changes

2023-09-19 15:17 UTC, vovasalyha commented on src/main/java/com/example/bookstore/security/JwtAuthenticationFilter.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
Spring's HttpHeaders class already has this constant, you can also consider using it

2023-09-19 15:17 UTC, vovasalyha commented on src/main/java/com/example/bookstore/service/book/BookServiceImpl.java
> +        List<Book> books = bookRepository.findAllByCategoryId(categoryId);
can be inlined

2023-09-29 14:16 UTC, merged