Add springboot-shoppingcart model
AntonZhdanov/Book-Store pull request #9
Opened 2023-09-19 19:42 UTC by AntonZhdanov

2023-09-20 14:09 UTC, IvanFadieiev requested changes
Good job!) Some small details to change :)

2023-09-20 14:09 UTC, IvanFadieiev commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    }
Please add role for this endpoint

2023-09-20 14:09 UTC, IvanFadieiev commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    }
Same here, add role please :)

2023-09-20 14:09 UTC, IvanFadieiev commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    }
Same here, add role please :)

2023-09-20 14:09 UTC, IvanFadieiev commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    }
Same here, add role please :)

2023-09-20 14:09 UTC, IvanFadieiev commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    @Operation(summary = "Add book to the shopping cart")
My recommendation is to change "book" to "cart item" because in this controller we are handling cart items, not books.
Same for every other "book" in this controller.

2023-09-20 14:09 UTC, IvanFadieiev commented on src/main/java/com/example/bookstore/mapper/CartItemMapper.java
> +    }
We can set all the missing fields in @Mapping annotation. Same as you did in ShoppingCartMapper.

2023-09-20 14:09 UTC, IvanFadieiev commented on src/main/java/com/example/bookstore/model/CartItem.java
> +    @ManyToOne
We have to indicate fetch type here

2023-09-25 07:19 UTC, IvanFadieiev approved these changes

2023-09-26 09:19 UTC, boroda4436 requested changes

2023-09-26 09:19 UTC, boroda4436 commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +@RequestMapping(value = "/api/cart")
`/api` could be moved to `application.properties` file

2023-09-26 09:19 UTC, boroda4436 commented on src/main/java/com/example/bookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    @Transactional
There is no need in this annotation here

2023-09-26 09:19 UTC, boroda4436 commented on src/main/java/com/example/bookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +        cartItemService.findById(id).setQuantity(updateQuantityInCartItemDto.quantity());
Shouldn't we save this cart item after the update?

2023-09-26 09:19 UTC, boroda4436 commented on src/main/java/com/example/bookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    public ShoppingCart getUserShoppingCart() {
it could be private

2023-09-26 09:19 UTC, boroda4436 commented on src/main/resources/db/changelog/changes/06-create-category-table.yaml
> -      author: anton
technically you should not update the existing changesets. But since you haven't deployed your app, you can do it locally

2023-09-26 09:19 UTC, boroda4436 commented on src/main/java/com/example/bookstore/service/cartitem/CartItemServiceImpl.java
> +        if (createCartItemRequestDto.getBookId() == null) {
Could be checked by `@Valid` annotation

2023-09-26 09:19 UTC, boroda4436 commented on src/main/java/com/example/bookstore/service/cartitem/CartItemService.java
> +    CartItem findById(Long id);
We will use `find` when the `Optional` should be returned
```suggestion
    CartItem getById(Long id);
```

2023-09-26 09:19 UTC, boroda4436 commented on src/main/java/com/example/bookstore/service/book/BookServiceImpl.java
> +                .collect(Collectors.toList());
You are using JDK 17, so feel free to use simpler approach
```suggestion
                .toList();
```

2023-09-27 06:56 UTC, boroda4436 approved these changes
Great job!

2023-09-29 16:58 UTC, merged